### ISSUE TITLE
Feature: Stylesheet optimization ruins CSS inlining

### ISSUE THREAD

**Issue by djibe** [Tom-Bonnike/netlify-plugin-inline-critical-css#19]
Hi,
Inline-critical was working perfectly.
So I decided to defer CSS loading with the trick
`<link rel=stylesheet href=style.min.css media=print onload="this.media='all'"`

But this ruins Critical CSS building. Seems like plugin doesn't find the stylesheet, and because CSS loading is defered all performances are ruined.

Thanks for your help

**Comment by Tom-Bonnike** [comment]
Hi. I’d need more info or an example site to understand the problem. `critical` already uses this media switching strategy for your non-inlined styles, you shouldn't have to implement it yourself? You may also need to know about https://github.com/netlify/build/issues/1384.

**Comment by djibe** [comment]
Hi, thanks for your reply.

I don't use any Netlify optimization.

When I switch from
`<link rel=stylesheet href=style.min.css`
to
`<link rel=stylesheet href=style.min.css media=print onload="this.media='all'"`

plugin doesn't detect my stylesheet and therefore doesn't inline critical styles.

This `<link rel=stylesheet href=style.min.css media=print onload="this.media='all'"` is a smart way to defer CSS loading for performances.

Thanks for your time.

Best,

**Comment by Tom-Bonnike** [comment]
`critical` should be applying this strategy for your non-inlined styles already, you should double check, you may not need to do this yourself.

I’m pretty sure `critical` will ignore `media="print"` stylesheets while parsing your HTML, see https://github.com/addyosmani/critical/blob/6b3e957ee2081dccb7113f23f4d648142687ef53/src/file.js#L376.

Closing, feel free to open an issue on https://github.com/addyosmani/critical if you think something is worth changing/fixing.

**Comment by djibe** [comment]
True.
Netlify builds seems to crash randomly and not because of the plugin.
Thanks for your time.

**Comment by djibe** [comment]
Sorry to be back.

Remade a commit with my stylesheet optimization only:
`<link rel=stylesheet href=style.min.css media=print onload="this.media='all'">`

Netlify sent me this:
(netlify-plugin-inline-critical-css onPostBuild completed in 6.5s)

The only <style> tag in my header was my @font-face declaration.

Reverted to
`<link rel=stylesheet href=style.min.css>`
and CSS inling is back.
