### ISSUE TITLE
Plugin "netlify-plugin-inline-critical-css" failed: Failed to launch the browser process!

### ISSUE THREAD

**Issue by djibe** [Tom-Bonnike/netlify-plugin-inline-critical-css#20]
Hi,
sorry to be back.

Since March 28 my Netlify builds are tricky.
Having CriticalCSS build crashes, I reverted to Hugo 0.81.0.
Build command is the simplest: ```hugo```
Critical config is the simplest
```
  [[plugins]]
  package = "netlify-plugin-inline-critical-css"
```
I checked all my files for HTML or script errors but all validators are green.

I still have these Netlify logs:

```
Plugin "netlify-plugin-inline-critical-css" failed

Error: Failed to inline critical CSS.
Failed to launch the browser process!
Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

In "onPostBuild" event in "netlify-plugin-inline-critical-css" from netlify.toml
at onClose (/.netlify/plugins/node_modules/puppeteer/lib/Launcher.js:750:14)
```

Don't you have this on your side ?
Thanks a lot,

JB

**Comment by Tom-Bonnike** [comment]
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14 this would probably help? What Node version are you using on CI? You should be able to use another one using the [`NODE_VERSION` environment variable](https://docs.netlify.com/configure-builds/environment-variables/#netlify-configuration-variables)

**Comment by Tom-Bonnike** [comment]
See https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/9, not much we can do sadly :(
It shouldn’t happen on every build tho.

**Comment by djibe** [comment]
You are awesome. Thanks a lot
