### ISSUE TITLE
Debugging help - file not found style.css, but not referenced in my site

### ISSUE THREAD

**Issue by christopherpickering** [Tom-Bonnike/netlify-plugin-inline-critical-css#22]
hey Tom, thanks for helping me out yesterday.. I'm running into another issue:

```sh
7:06:01 AM: ────────────────────────────────────────────────────────────────
7:06:01 AM:   Plugin "netlify-plugin-inline-critical-css" failed            
7:06:01 AM: ────────────────────────────────────────────────────────────────
7:06:01 AM: ​
7:06:01 AM:   Error message
7:06:01 AM:   Error: Failed to inline critical CSS.
7:06:01 AM:   Error: File not found: style.css
7:06:01 AM:          Current working directory: /opt/build/repo
7:06:01 AM:          Searched in: /opt/build/repo, /opt/build/repo/static/font/Inter
```

I've tried running the command locally, but not sure where to begin debugging it! I do not have any files called "style.css".

The site I'm trying to build is https://github.com/Riverside-Healthcare/Atlas-Website/tree/netlify

In Netlify I have your plugin installed, but for testing locally I just added your sample ```netlify.toml``` from the read me.

If you have any tips to point me in the right direction I'd appreciate it!

**Comment by Tom-Bonnike** [comment]
You do seem to have a `style.css` linked in https://github.com/Riverside-Healthcare/Atlas-Website/blob/e6d8a923b06f1c70c799d73bb56e21460a9fbd3b/web/static/font/Inter/example.html. Looks like it should be `stylesheet.css`.

The plugin runs on all `.html` files in the repo, which is why it tries to run on your Inter font’s example files.

**Comment by christopherpickering** [comment]
Thanks for checking it out! I appreciate it.

**Comment by christopherpickering** [comment]
Works well now, thanks! 
![sailboat](https://media.giphy.com/media/Ang2cRgTTJW5W/giphy.gif)
