### ISSUE TITLE
postcss-discard: postcss.plugin was deprecated

### ISSUE THREAD

**Issue by rokib-rajon** [Tom-Bonnike/netlify-plugin-inline-critical-css#23]
It takes longer time to build, please update the plugin. 

![image](https://user-images.githubusercontent.com/55991864/128957641-cfa5768e-3f49-49b2-b6ba-ebdc7555b4f0.png)

**Comment by WebShapedBiz** [comment]
Same here, it takes a very long time to process. I don't really know how much speed is PostCSS 8.0 bringing, but it would be nice to see this plugin updated.

![ksnip_20211208-105035](https://user-images.githubusercontent.com/6765137/145187347-8ae7e21d-9e1b-4f6e-acb1-cb7b4fe15461.png)

Cheers.

**Comment by Tom-Bonnike** [comment]
Fixed with [v2.0.0](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/blob/master/CHANGELOG.md), thanks! Follow https://github.com/netlify/plugins/pull/530 for the release into the Plugins directory.

**Comment by WebShapedBiz** [comment]
Thank you very much @Tom-Bonnike for your time and effort.
