### ISSUE TITLE
Resolve it's own dependencies

### ISSUE THREAD

**Issue by chris-short** [Tom-Bonnike/netlify-plugin-inline-critical-css#24]
To test Netlify plugins I add them manually via the UI. With this plugin I had a very log build, then a failure because npm or yarn wasn't installed. I would suggest that, if possible, this plugin check its environment first then resolve any missing dependencies.

If you're not able to do that due to something at Netlify, I will happily bark up their tree.

Thank you for the work on this.

**Comment by Tom-Bonnike** [comment]
npm or Yarn not being installed seems fishy; what Netlify build image are you using? 🤔
