### ISSUE TITLE
Error `Cannot read property 'walkDecls' of undefined`

### ISSUE THREAD

**Issue by ehmicky** [Tom-Bonnike/netlify-plugin-inline-critical-css#7]
The following error is happening in some builds:

```
@media (min-width:320px) and (max-width:480px){{padding-top:65px;overflow-x:hidden !important;height:100% !important;}}/*!sc*/
data-styled.g145[id="sc-global-jYygkk1"]{content:"sc-global-jYygkk1,"}/*!sc*/
<css input>:13:267730: Missed semicolon

┌────────────────────────────────────────────────────┐
│ Plugin "netlify-plugin-inline-critical-css" failed │
└────────────────────────────────────────────────────┘

Error message
TypeError: Failed to inline critical CSS.
Cannot read property 'walkDecls' of undefined 
    /opt/buildhome/.netlify-build-plugins/node_modules/postcss-discard/index.js:98:7 getCssMapping
    /opt/buildhome/.netlify-build-plugins/node_modules/postcss-discard/index.js:169:21 
    /opt/buildhome/.netlify-build-plugins/node_modules/postcss/lib/postcss.js:133:35 creator
    /opt/buildhome/.netlify-build-plugins/node_modules/inline-critical/src/css.js:42:20 extractCss
    /opt/buildhome/.netlify-build-plugins/node_modules/inline-critical/index.js:66:25 inline
    /opt/buildhome/.netlify-build-plugins/node_modules/critical/src/core.js:222:21 create
    internal/process/task_queues.js:97:5 processTicksAndRejections
    /opt/buildhome/.netlify-build-plugins/node_modules/critical/index.js:23:20 async generate
```

Do you know what the error might be?

**Comment by Tom-Bonnike** [comment]
Seems like it’s caused by invalid CSS, like the error says, it’s missing a semicolon.https://github.com/bezoerb/postcss-discard/blob/6063d47a6ae7ff56f3f983cd953513abceb8423f/index.js#L85:L95

**Comment by Tom-Bonnike** [comment]
`postcss-discard` tries to get the CSS AST using `postcss` but it fails to parse the CSS because it’s invalid.
https://github.com/bezoerb/postcss-discard/blob/6063d47a6ae7ff56f3f983cd953513abceb8423f/index.js#L85:L95

Like the error says, it’s caused by a missing semicolon in the user’s CSS. However the CSS printed by `postcss` in the stacktrace seems valid, I tried it on a PostCSS REPL. Either this isn‘t the full log or it’s printing the wrong part of the code 🤷‍♂️

Anyway, this is something that should be fixed by the user. Not sure what I should be doing, `utils.failBuild` is expected here, no?

**Comment by ehmicky** [comment]
This might be more of a problem with `postcss-discard` but some users might misunderstand this as a bug in this plugin due to the error message `Cannot read property 'walkDecls' of undefined`. Without looking into its code, at first sight, they might skip the `Missing semicolon` line and focus on the error message below.

It seems to me `postcss-discard` should have some way to throw an error instead of [printing it](https://github.com/bezoerb/postcss-discard/blob/6063d47a6ae7ff56f3f983cd953513abceb8423f/index.js#L93) on console. Like this, consumers like you could report those errors in a better way.

However, `utils.build.failBuild()` is indeed correct there since this is a user error, so I am closing this issue :)
Thanks for the explanation!

**Comment by Tom-Bonnike** [comment]
Opened https://github.com/bezoerb/postcss-discard/pull/22
